//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.WebServiceUpg2Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectOwner", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class ObjectOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealEstateBroker", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class RealEstateBroker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BrokerSsnr {
            get {
                return this.BrokerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerSsnrField, value) != true)) {
                    this.BrokerSsnrField = value;
                    this.RaisePropertyChanged("BrokerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BrokerAddress {
            get {
                return this.BrokerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerAddressField, value) != true)) {
                    this.BrokerAddressField = value;
                    this.RaisePropertyChanged("BrokerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Showing", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class Showing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ObjNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowingDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ObjNr {
            get {
                return this.ObjNrField;
            }
            set {
                if ((this.ObjNrField.Equals(value) != true)) {
                    this.ObjNrField = value;
                    this.RaisePropertyChanged("ObjNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BuyerSsnr {
            get {
                return this.BuyerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerSsnrField, value) != true)) {
                    this.BuyerSsnrField = value;
                    this.RaisePropertyChanged("BuyerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ShowingDate {
            get {
                return this.ShowingDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowingDateField, value) != true)) {
                    this.ShowingDateField = value;
                    this.RaisePropertyChanged("ShowingDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectiveBuyer", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class ProspectiveBuyer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuyerSsnrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNr {
            get {
                return this.PhoneNrField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNrField, value) != true)) {
                    this.PhoneNrField = value;
                    this.RaisePropertyChanged("PhoneNr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BuyerSsnr {
            get {
                return this.BuyerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BuyerSsnrField, value) != true)) {
                    this.BuyerSsnrField = value;
                    this.RaisePropertyChanged("BuyerSsnr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RealEstateObject", Namespace="http://brokerapplication.org/")]
    [System.SerializableAttribute()]
    public partial class RealEstateObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageField;
        
        private int ObjnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjCityField;
        
        private int ObjPriceField;
        
        private int ObjAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjRoomsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokerSsnrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerSsnrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Objnr {
            get {
                return this.ObjnrField;
            }
            set {
                if ((this.ObjnrField.Equals(value) != true)) {
                    this.ObjnrField = value;
                    this.RaisePropertyChanged("Objnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ObjAddress {
            get {
                return this.ObjAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjAddressField, value) != true)) {
                    this.ObjAddressField = value;
                    this.RaisePropertyChanged("ObjAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ObjCity {
            get {
                return this.ObjCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjCityField, value) != true)) {
                    this.ObjCityField = value;
                    this.RaisePropertyChanged("ObjCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int ObjPrice {
            get {
                return this.ObjPriceField;
            }
            set {
                if ((this.ObjPriceField.Equals(value) != true)) {
                    this.ObjPriceField = value;
                    this.RaisePropertyChanged("ObjPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ObjArea {
            get {
                return this.ObjAreaField;
            }
            set {
                if ((this.ObjAreaField.Equals(value) != true)) {
                    this.ObjAreaField = value;
                    this.RaisePropertyChanged("ObjArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ObjRooms {
            get {
                return this.ObjRoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjRoomsField, value) != true)) {
                    this.ObjRoomsField = value;
                    this.RaisePropertyChanged("ObjRooms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UnitType {
            get {
                return this.UnitTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitTypeField, value) != true)) {
                    this.UnitTypeField = value;
                    this.RaisePropertyChanged("UnitType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ObjInfo {
            get {
                return this.ObjInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjInfoField, value) != true)) {
                    this.ObjInfoField = value;
                    this.RaisePropertyChanged("ObjInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string BrokerSsnr {
            get {
                return this.BrokerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokerSsnrField, value) != true)) {
                    this.BrokerSsnrField = value;
                    this.RaisePropertyChanged("BrokerSsnr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string OwnerSsnr {
            get {
                return this.OwnerSsnrField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerSsnrField, value) != true)) {
                    this.OwnerSsnrField = value;
                    this.RaisePropertyChanged("OwnerSsnr");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://brokerapplication.org/", ConfigurationName="WebServiceUpg2Reference.WebServiceUpg2Soap")]
    public interface WebServiceUpg2Soap {
        
        // CODEGEN: Generating message contract since element name errorMessage from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetObjectOwner", ReplyAction="*")]
        WebService.WebServiceUpg2Reference.GetObjectOwnerResponse GetObjectOwner(WebService.WebServiceUpg2Reference.GetObjectOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name GetRealEstateBrokerResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateBroker", ReplyAction="*")]
        WebService.WebServiceUpg2Reference.GetRealEstateBrokerResponse GetRealEstateBroker(WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequest request);
        
        // CODEGEN: Generating message contract since element name GetShowingResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetShowing", ReplyAction="*")]
        WebService.WebServiceUpg2Reference.GetShowingResponse GetShowing(WebService.WebServiceUpg2Reference.GetShowingRequest request);
        
        // CODEGEN: Generating message contract since element name GetProspectiveBuyersResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetProspectiveBuyers", ReplyAction="*")]
        WebService.WebServiceUpg2Reference.GetProspectiveBuyersResponse GetProspectiveBuyers(WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequest request);
        
        // CODEGEN: Generating message contract since element name GetRealEstateObjectsResult from namespace http://brokerapplication.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://brokerapplication.org/GetRealEstateObjects", ReplyAction="*")]
        WebService.WebServiceUpg2Reference.GetRealEstateObjectsResponse GetRealEstateObjects(WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwner", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body;
        
        public GetObjectOwnerRequest() {
        }
        
        public GetObjectOwnerRequest(WebService.WebServiceUpg2Reference.GetObjectOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetObjectOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string errorMessage;
        
        public GetObjectOwnerRequestBody() {
        }
        
        public GetObjectOwnerRequestBody(string errorMessage) {
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjectOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjectOwnerResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body;
        
        public GetObjectOwnerResponse() {
        }
        
        public GetObjectOwnerResponse(WebService.WebServiceUpg2Reference.GetObjectOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetObjectOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.WebServiceUpg2Reference.ObjectOwner[] GetObjectOwnerResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public GetObjectOwnerResponseBody() {
        }
        
        public GetObjectOwnerResponseBody(WebService.WebServiceUpg2Reference.ObjectOwner[] GetObjectOwnerResult, string errorMessage) {
            this.GetObjectOwnerResult = GetObjectOwnerResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBroker", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body;
        
        public GetRealEstateBrokerRequest() {
        }
        
        public GetRealEstateBrokerRequest(WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRealEstateBrokerRequestBody {
        
        public GetRealEstateBrokerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateBrokerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateBrokerResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body;
        
        public GetRealEstateBrokerResponse() {
        }
        
        public GetRealEstateBrokerResponse(WebService.WebServiceUpg2Reference.GetRealEstateBrokerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetRealEstateBrokerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.WebServiceUpg2Reference.RealEstateBroker[] GetRealEstateBrokerResult;
        
        public GetRealEstateBrokerResponseBody() {
        }
        
        public GetRealEstateBrokerResponseBody(WebService.WebServiceUpg2Reference.RealEstateBroker[] GetRealEstateBrokerResult) {
            this.GetRealEstateBrokerResult = GetRealEstateBrokerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShowingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShowing", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetShowingRequestBody Body;
        
        public GetShowingRequest() {
        }
        
        public GetShowingRequest(WebService.WebServiceUpg2Reference.GetShowingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetShowingRequestBody {
        
        public GetShowingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetShowingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetShowingResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetShowingResponseBody Body;
        
        public GetShowingResponse() {
        }
        
        public GetShowingResponse(WebService.WebServiceUpg2Reference.GetShowingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetShowingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.WebServiceUpg2Reference.Showing[] GetShowingResult;
        
        public GetShowingResponseBody() {
        }
        
        public GetShowingResponseBody(WebService.WebServiceUpg2Reference.Showing[] GetShowingResult) {
            this.GetShowingResult = GetShowingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProspectiveBuyersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProspectiveBuyers", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody Body;
        
        public GetProspectiveBuyersRequest() {
        }
        
        public GetProspectiveBuyersRequest(WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProspectiveBuyersRequestBody {
        
        public GetProspectiveBuyersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProspectiveBuyersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProspectiveBuyersResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetProspectiveBuyersResponseBody Body;
        
        public GetProspectiveBuyersResponse() {
        }
        
        public GetProspectiveBuyersResponse(WebService.WebServiceUpg2Reference.GetProspectiveBuyersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetProspectiveBuyersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.WebServiceUpg2Reference.ProspectiveBuyer[] GetProspectiveBuyersResult;
        
        public GetProspectiveBuyersResponseBody() {
        }
        
        public GetProspectiveBuyersResponseBody(WebService.WebServiceUpg2Reference.ProspectiveBuyer[] GetProspectiveBuyersResult) {
            this.GetProspectiveBuyersResult = GetProspectiveBuyersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateObjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateObjects", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody Body;
        
        public GetRealEstateObjectsRequest() {
        }
        
        public GetRealEstateObjectsRequest(WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRealEstateObjectsRequestBody {
        
        public GetRealEstateObjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRealEstateObjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRealEstateObjectsResponse", Namespace="http://brokerapplication.org/", Order=0)]
        public WebService.WebServiceUpg2Reference.GetRealEstateObjectsResponseBody Body;
        
        public GetRealEstateObjectsResponse() {
        }
        
        public GetRealEstateObjectsResponse(WebService.WebServiceUpg2Reference.GetRealEstateObjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://brokerapplication.org/")]
    public partial class GetRealEstateObjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebService.WebServiceUpg2Reference.RealEstateObject[] GetRealEstateObjectsResult;
        
        public GetRealEstateObjectsResponseBody() {
        }
        
        public GetRealEstateObjectsResponseBody(WebService.WebServiceUpg2Reference.RealEstateObject[] GetRealEstateObjectsResult) {
            this.GetRealEstateObjectsResult = GetRealEstateObjectsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg2SoapChannel : WebService.WebServiceUpg2Reference.WebServiceUpg2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg2SoapClient : System.ServiceModel.ClientBase<WebService.WebServiceUpg2Reference.WebServiceUpg2Soap>, WebService.WebServiceUpg2Reference.WebServiceUpg2Soap {
        
        public WebServiceUpg2SoapClient() {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg2Reference.GetObjectOwnerResponse WebService.WebServiceUpg2Reference.WebServiceUpg2Soap.GetObjectOwner(WebService.WebServiceUpg2Reference.GetObjectOwnerRequest request) {
            return base.Channel.GetObjectOwner(request);
        }
        
        public WebService.WebServiceUpg2Reference.ObjectOwner[] GetObjectOwner(ref string errorMessage) {
            WebService.WebServiceUpg2Reference.GetObjectOwnerRequest inValue = new WebService.WebServiceUpg2Reference.GetObjectOwnerRequest();
            inValue.Body = new WebService.WebServiceUpg2Reference.GetObjectOwnerRequestBody();
            inValue.Body.errorMessage = errorMessage;
            WebService.WebServiceUpg2Reference.GetObjectOwnerResponse retVal = ((WebService.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetObjectOwner(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.GetObjectOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg2Reference.GetRealEstateBrokerResponse WebService.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateBroker(WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequest request) {
            return base.Channel.GetRealEstateBroker(request);
        }
        
        public WebService.WebServiceUpg2Reference.RealEstateBroker[] GetRealEstateBroker() {
            WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequest inValue = new WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequest();
            inValue.Body = new WebService.WebServiceUpg2Reference.GetRealEstateBrokerRequestBody();
            WebService.WebServiceUpg2Reference.GetRealEstateBrokerResponse retVal = ((WebService.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateBroker(inValue);
            return retVal.Body.GetRealEstateBrokerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg2Reference.GetShowingResponse WebService.WebServiceUpg2Reference.WebServiceUpg2Soap.GetShowing(WebService.WebServiceUpg2Reference.GetShowingRequest request) {
            return base.Channel.GetShowing(request);
        }
        
        public WebService.WebServiceUpg2Reference.Showing[] GetShowing() {
            WebService.WebServiceUpg2Reference.GetShowingRequest inValue = new WebService.WebServiceUpg2Reference.GetShowingRequest();
            inValue.Body = new WebService.WebServiceUpg2Reference.GetShowingRequestBody();
            WebService.WebServiceUpg2Reference.GetShowingResponse retVal = ((WebService.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetShowing(inValue);
            return retVal.Body.GetShowingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg2Reference.GetProspectiveBuyersResponse WebService.WebServiceUpg2Reference.WebServiceUpg2Soap.GetProspectiveBuyers(WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequest request) {
            return base.Channel.GetProspectiveBuyers(request);
        }
        
        public WebService.WebServiceUpg2Reference.ProspectiveBuyer[] GetProspectiveBuyers() {
            WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequest inValue = new WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequest();
            inValue.Body = new WebService.WebServiceUpg2Reference.GetProspectiveBuyersRequestBody();
            WebService.WebServiceUpg2Reference.GetProspectiveBuyersResponse retVal = ((WebService.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetProspectiveBuyers(inValue);
            return retVal.Body.GetProspectiveBuyersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg2Reference.GetRealEstateObjectsResponse WebService.WebServiceUpg2Reference.WebServiceUpg2Soap.GetRealEstateObjects(WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequest request) {
            return base.Channel.GetRealEstateObjects(request);
        }
        
        public WebService.WebServiceUpg2Reference.RealEstateObject[] GetRealEstateObjects() {
            WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequest inValue = new WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequest();
            inValue.Body = new WebService.WebServiceUpg2Reference.GetRealEstateObjectsRequestBody();
            WebService.WebServiceUpg2Reference.GetRealEstateObjectsResponse retVal = ((WebService.WebServiceUpg2Reference.WebServiceUpg2Soap)(this)).GetRealEstateObjects(inValue);
            return retVal.Body.GetRealEstateObjectsResult;
        }
    }
}
