//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.WebServiceUpg1Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceUpg1Reference.WebServiceUpg1Soap")]
    public interface WebServiceUpg1Soap {
        
        // CODEGEN: Generating message contract since element name filename from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Metod1", ReplyAction="*")]
        WebService.WebServiceUpg1Reference.Metod1Response Metod1(WebService.WebServiceUpg1Reference.Metod1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metod1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metod1", Namespace="http://tempuri.org/", Order=0)]
        public WebService.WebServiceUpg1Reference.Metod1RequestBody Body;
        
        public Metod1Request() {
        }
        
        public Metod1Request(WebService.WebServiceUpg1Reference.Metod1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metod1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filename;
        
        public Metod1RequestBody() {
        }
        
        public Metod1RequestBody(string filename) {
            this.filename = filename;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Metod1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Metod1Response", Namespace="http://tempuri.org/", Order=0)]
        public WebService.WebServiceUpg1Reference.Metod1ResponseBody Body;
        
        public Metod1Response() {
        }
        
        public Metod1Response(WebService.WebServiceUpg1Reference.Metod1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Metod1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Metod1Result;
        
        public Metod1ResponseBody() {
        }
        
        public Metod1ResponseBody(string Metod1Result) {
            this.Metod1Result = Metod1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceUpg1SoapChannel : WebService.WebServiceUpg1Reference.WebServiceUpg1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceUpg1SoapClient : System.ServiceModel.ClientBase<WebService.WebServiceUpg1Reference.WebServiceUpg1Soap>, WebService.WebServiceUpg1Reference.WebServiceUpg1Soap {
        
        public WebServiceUpg1SoapClient() {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceUpg1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.WebServiceUpg1Reference.Metod1Response WebService.WebServiceUpg1Reference.WebServiceUpg1Soap.Metod1(WebService.WebServiceUpg1Reference.Metod1Request request) {
            return base.Channel.Metod1(request);
        }
        
        public string Metod1(string filename) {
            WebService.WebServiceUpg1Reference.Metod1Request inValue = new WebService.WebServiceUpg1Reference.Metod1Request();
            inValue.Body = new WebService.WebServiceUpg1Reference.Metod1RequestBody();
            inValue.Body.filename = filename;
            WebService.WebServiceUpg1Reference.Metod1Response retVal = ((WebService.WebServiceUpg1Reference.WebServiceUpg1Soap)(this)).Metod1(inValue);
            return retVal.Body.Metod1Result;
        }
    }
}
